//! Operator parity against spyder_ref goldens on synthetic inputs (tests/goldens/operators_v1.json,
//! generated by tests/gen/gen_operator_goldens.py), plus property tests that need no Python.

#![allow(clippy::field_reassign_with_default, clippy::needless_range_loop)] // test fixtures read better this way

use serde_json::Value;
use spyder_core::n2::n2;
use spyder_core::numsum::{np_mean, np_std, np_sum};
use spyder_core::preprocess::savgol::{in_table, sg_weights};
use spyder_core::preprocess::{
    parse_chain, parse_op, run_chain, OpError, PerSegment, RadiusRule, Spectrum,
};

fn goldens() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/goldens/operators_v1.json"
    );
    let text = std::fs::read_to_string(path).expect("read goldens");
    serde_json::from_str(&text).expect("parse goldens")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().unwrap_or(f64::NAN))
        .collect()
}

fn close(got: f64, want: f64, abs: f64, rel: f64) -> bool {
    if want.is_nan() {
        return got.is_nan();
    }
    (got - want).abs() <= abs + rel * want.abs()
}

/// Operator outputs: the PLAN gate is 1e-9 + 1e-9|v|; we hold them to 1e-12 (platform log10/exp/pow ulps only).
const OP_ABS: f64 = 1e-12;
const OP_REL: f64 = 1e-12;

#[test]
fn operator_cases_match_spyder_ref() {
    let g = goldens();
    let spectra = &g["spectra"];
    let mut n_values = 0usize;
    let mut worst = 0.0f64;
    let mut n_cases = 0;
    for case in g["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let sp = &spectra[case["spectrum"].as_str().unwrap()];
        let s = Spectrum::new(f64s(&sp["wl"]), f64s(&sp["values"]));
        let joins = f64s(&case["joins"]);
        let parsed = parse_chain(&case["chain"]);
        if let Some(kind) = case.get("expect_error").and_then(Value::as_str) {
            let err = match parsed {
                Err(e) => e,
                Ok(chain) => run_chain(&chain, &s, &joins).expect_err(name),
            };
            let got = match err {
                OpError::UnsupportedOperator { .. } => "unsupported_operator",
                OpError::UnknownOperator { .. } => "unknown_operator",
                OpError::InvalidParameters { .. } => "invalid_parameters",
                OpError::Failed { .. } => "failed",
            };
            assert_eq!(got, kind, "{name}: {err}");
            n_cases += 1;
            continue;
        }
        let chain = parsed.unwrap_or_else(|e| panic!("{name}: {e}"));
        let out = run_chain(&chain, &s, &joins).unwrap_or_else(|e| panic!("{name}: {e}"));
        let want = f64s(&case["expected"]);
        assert_eq!(out.x.len(), want.len(), "{name}: length");
        if let Some(grid) = case.get("expected_grid") {
            let (first, step) = (
                grid["first"].as_f64().unwrap(),
                grid["step"].as_f64().unwrap(),
            );
            for (i, w) in out.wl.iter().enumerate() {
                assert!((w - (first + step * i as f64)).abs() < 1e-9, "{name}: grid");
            }
        } else {
            assert_eq!(out.wl, f64s(&case["expected_wl"]), "{name}: grid");
        }
        for (i, (&a, &b)) in out.x.iter().zip(&want).enumerate() {
            assert!(
                close(a, b, OP_ABS, OP_REL),
                "{name}: value {i}: got {a:e}, want {b:e}, diff {:e}",
                (a - b).abs()
            );
            if b.is_finite() {
                worst = worst.max((a - b).abs() / (1.0 + b.abs()));
            }
        }
        n_values += want.len();
        n_cases += 1;
    }
    assert!(n_cases >= 50, "only {n_cases} cases ran");
    println!("{n_cases} operator cases, {n_values} values, worst |diff|/(1+|v|) = {worst:e}");
}

#[test]
fn sg_weights_bitwise_for_table_and_close_otherwise() {
    let g = goldens();
    let (mut bitwise, mut fallback) = (0, 0);
    for e in g["sg_weights"].as_array().unwrap() {
        let w = e["window"].as_u64().unwrap() as usize;
        let p = e["polyorder"].as_u64().unwrap() as usize;
        let d = e["deriv"].as_u64().unwrap() as usize;
        let delta = e["delta"].as_f64().unwrap();
        let table = e["table"].as_bool().unwrap();
        assert_eq!(in_table(w, p, d), table, "table membership W{w} P{p} d{d}");
        let got = sg_weights(w, p, d, delta);
        let mut rows = vec![(got.centre.clone(), f64s(&e["centre"]))];
        if let Some(left) = e.get("left") {
            for (r, want) in left.as_array().unwrap().iter().enumerate() {
                rows.push((got.left[r].clone(), f64s(want)));
            }
            for (r, want) in e["right"].as_array().unwrap().iter().enumerate() {
                rows.push((got.right[r].clone(), f64s(want)));
            }
        }
        for (gr, wr) in rows {
            assert_eq!(gr.len(), wr.len());
            let scale = wr.iter().fold(0.0f64, |m, x| m.max(x.abs()));
            for (a, b) in gr.iter().zip(&wr) {
                if table {
                    assert_eq!(
                        a.to_bits(),
                        b.to_bits(),
                        "W{w} P{p} d{d} delta {delta}: {a:e} vs {b:e}"
                    );
                } else {
                    assert!(
                        (a - b).abs() <= 1e-13 * scale,
                        "fallback W{w} P{p} d{d}: {a:e} vs {b:e}"
                    );
                }
            }
        }
        if table {
            bitwise += 1;
        } else {
            fallback += 1;
        }
    }
    assert!(
        bitwise >= 38 && fallback >= 20,
        "{bitwise} table, {fallback} fallback"
    );
}

#[test]
fn qr_fallback_agrees_with_table() {
    // every table combination recomputed by the QR path: within 1e-13 of the largest frozen weight
    for &(w, p, d) in &[(31, 3, 2), (23, 2, 1), (35, 2, 1), (49, 3, 1), (11, 2, 1)] {
        let h = w / 2;
        let qr = spyder_core::preprocess::savgol::sg_unscaled_qr(w, p, d, &[h]);
        let div = (h as f64).powi(d as i32);
        let t = sg_weights(w, p, d, 1.0);
        let scale = t.centre.iter().fold(0.0f64, |m, x| m.max(x.abs()));
        for (a, b) in qr[0].iter().zip(&t.centre) {
            assert!(
                (a / div - b).abs() <= 1e-13 * scale,
                "W{w}: {:e} {b:e}",
                a / div
            );
        }
    }
}

#[test]
fn numpy_summation_bitwise() {
    let g = goldens();
    for c in g["np_sum"].as_array().unwrap() {
        let v = f64s(&c["values"]);
        let n = v.len();
        assert_eq!(
            np_sum(&v).to_bits(),
            c["sum"].as_f64().unwrap().to_bits(),
            "sum n={n}"
        );
        assert_eq!(
            np_mean(&v).to_bits(),
            c["mean"].as_f64().unwrap().to_bits(),
            "mean n={n}"
        );
        assert_eq!(
            np_std(&v, 0).to_bits(),
            c["std0"].as_f64().unwrap().to_bits(),
            "std n={n}"
        );
        if let Some(s1) = c["std1"].as_f64() {
            assert_eq!(np_std(&v, 1).to_bits(), s1.to_bits(), "std ddof1 n={n}");
        }
    }
}

#[test]
fn n2_matches_n2_py_on_synthetic_spectra() {
    let g = goldens();
    for c in g["n2"].as_array().unwrap() {
        let wl = f64s(&c["wl"]);
        let r = f64s(&c["reflectance"]);
        for (key, want) in c["n2"].as_object().unwrap() {
            let (lo, hi) = key.split_once('_').unwrap();
            let got = n2(&r, &wl, lo.parse().unwrap(), hi.parse().unwrap());
            match want.as_f64() {
                None => assert_eq!(got, None, "{key}"),
                Some(w) => {
                    let gv = got.expect("n2 defined");
                    assert!(
                        (gv - w).abs() <= 1e-12 * w.abs().max(1.0),
                        "{key}: {gv} vs {w}"
                    );
                }
            }
        }
    }
}

// ------------------------------------------------------------------------- property tests (no Python)

/// Deterministic xorshift for test inputs.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> f64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        (self.0 >> 11) as f64 / (1u64 << 53) as f64
    }
}

#[test]
fn sg_on_polynomials_gives_exact_derivatives() {
    let mut rng = Rng(0x9E3779B97F4A7C15);
    for &(w, p) in &[
        (5usize, 2usize),
        (11, 2),
        (11, 3),
        (23, 2),
        (31, 3),
        (21, 4),
        (51, 5),
        (17, 3),
    ] {
        for d in 0..=p.min(4) {
            for deg in 0..=p {
                // random polynomial of degree `deg` in t (sample index), coefficients O(1) on a scaled t
                let coef: Vec<f64> = (0..=deg).map(|_| rng.next() * 2.0 - 1.0).collect();
                let n = 80usize;
                let scale = 40.0;
                let poly = |t: f64, k: usize| -> f64 {
                    // k-th derivative wrt t of sum c_m (t/scale)^m
                    let mut s = 0.0;
                    for (m, c) in coef.iter().enumerate() {
                        if m >= k {
                            let f: f64 = ((m - k + 1)..=m).map(|x| x as f64).product();
                            s += c * f * (t / scale).powi((m - k) as i32) / scale.powi(k as i32);
                        }
                    }
                    s
                };
                let x: Vec<f64> = (0..n).map(|t| poly(t as f64, 0)).collect();
                let wl: Vec<f64> = (0..n).map(|t| 1000.0 + t as f64).collect();
                for mode in ["interp", "zero_edges", "valid"] {
                    let op = parse_op(&serde_json::json!({
                        "op": "savgol", "window": w, "polyorder": p, "deriv": d, "delta": 1.0, "mode": mode
                    }))
                    .unwrap();
                    let out = run_chain(&[op], &Spectrum::new(wl.clone(), x.clone()), &[]).unwrap();
                    let h = w / 2;
                    for (i, (&wv, &y)) in out.wl.iter().zip(&out.x).enumerate() {
                        let t = wv - 1000.0;
                        let interior = (h..n - h).contains(&(t as usize));
                        let want = if mode == "zero_edges" && !interior {
                            0.0
                        } else {
                            poly(t, d)
                        };
                        let tol = 1e-12 * (1.0 + want.abs());
                        assert!(
                            (y - want).abs() <= tol,
                            "W{w} P{p} d{d} deg{deg} {mode} i{i}: {y:e} vs {want:e}"
                        );
                    }
                }
            }
        }
    }
}

fn blur(sigma: PerSegment, radius: RadiusRule) -> spyder_core::preprocess::Op {
    spyder_core::preprocess::Op::GaussianBlur {
        sigma_nm: sigma,
        truncate: 4.0,
        radius,
    }
}

#[test]
fn blur_preserves_constants_and_never_crosses_a_join() {
    let wl: Vec<f64> = (0..2151).map(|i| 350.0 + i as f64).collect();
    let joins = [1000.0, 1800.0];
    // a constant spectrum is unchanged
    let s = Spectrum::new(wl.clone(), vec![0.37; wl.len()]);
    for r in [RadiusRule::Ceil, RadiusRule::Round] {
        for sig in [
            PerSegment::Scalar(3.3973),
            PerSegment::Segments(vec![0.0, 3.3973, 3.3973]),
            PerSegment::Scalar(25.0),
        ] {
            let out = run_chain(&[blur(sig, r)], &s, &joins).unwrap();
            assert!(out.x.iter().all(|v| (v - 0.37).abs() <= 1e-15), "constant");
        }
    }
    // a spectrum constant within each detector but stepped at the joins: unchanged (taps never cross)
    let stepped: Vec<f64> = wl
        .iter()
        .map(|&w| {
            if w <= 1000.0 {
                0.2
            } else if w <= 1800.0 {
                0.5
            } else {
                0.3
            }
        })
        .collect();
    let s = Spectrum::new(wl.clone(), stepped.clone());
    let out = run_chain(
        &[blur(PerSegment::Scalar(10.0), RadiusRule::Ceil)],
        &s,
        &joins,
    )
    .unwrap();
    for (a, b) in out.x.iter().zip(&stepped) {
        assert!((a - b).abs() <= 1e-15);
    }
    // ... but with different joins the step at 1000 is blurred into the neighbouring channels
    let out = run_chain(
        &[blur(PerSegment::Scalar(10.0), RadiusRule::Ceil)],
        &s,
        &[1800.0],
    )
    .unwrap();
    assert!((out.x[650] - 0.2).abs() > 1e-3);
}

#[test]
fn sigma_count_must_match_segments() {
    let wl: Vec<f64> = (0..300).map(|i| 900.0 + i as f64).collect();
    let s = Spectrum::new(wl, vec![0.3; 300]);
    // grid 900-1199 has 2 segments for joins 1000/1800 (1800 is beyond the grid)
    let e = run_chain(
        &[blur(
            PerSegment::Segments(vec![0.0, 1.0, 1.0]),
            RadiusRule::Ceil,
        )],
        &s,
        &[1000.0, 1800.0],
    )
    .unwrap_err();
    assert!(matches!(e, OpError::Failed { .. }), "{e}");
}

#[test]
fn block_snv_removes_block_gain_and_offset() {
    let wl: Vec<f64> = (0..2151).map(|i| 350.0 + i as f64).collect();
    let mut rng = Rng(42);
    let x: Vec<f64> = wl.iter().map(|_| rng.next()).collect();
    let op = parse_op(
        &serde_json::json!({"op": "snv", "ddof": 0, "blocks_nm": [[1480, 1650], [1990, 2250]]}),
    )
    .unwrap();
    let base = run_chain(
        std::slice::from_ref(&op),
        &Spectrum::new(wl.clone(), x.clone()),
        &[1000.0, 1800.0],
    )
    .unwrap();
    // a different gain and offset in each block leaves the output unchanged
    let y: Vec<f64> = wl
        .iter()
        .zip(&x)
        .map(|(&w, &v)| {
            if w < 1800.0 {
                1.7 * v + 0.3
            } else {
                0.6 * v - 2.0
            }
        })
        .collect();
    let out = run_chain(&[op], &Spectrum::new(wl, y), &[1000.0, 1800.0]).unwrap();
    assert_eq!(out.wl, base.wl);
    assert_eq!(out.wl.len(), 171 + 261);
    for (a, b) in out.x.iter().zip(&base.x) {
        assert!((a - b).abs() < 1e-12);
    }
}

#[test]
fn absorbance_affine_identity_and_clip() {
    let wl: Vec<f64> = (0..100).map(|i| 1500.0 + i as f64).collect();
    let x: Vec<f64> = (0..100).map(|i| 0.05 + 0.009 * i as f64).collect();
    let s = Spectrum::new(wl, x.clone());
    let op = parse_op(&serde_json::json!({"op": "absorbance_affine", "gain": 1.0, "offset": 0.0, "clip_min": 1e-6})).unwrap();
    let out = run_chain(&[op], &s, &[1000.0, 1800.0]).unwrap();
    for (a, b) in out.x.iter().zip(&x) {
        assert!((a - b).abs() <= 4e-16 * b.abs().max(1.0));
    }
    // absorbance clip: R <= clip gives -log10(clip); NaN propagates
    let a = spyder_core::preprocess::absorbance(&[0.0, -1.0, 1e-7, f64::NAN, 1.0], 1e-6);
    assert_eq!(a[0], 6.0);
    assert_eq!(a[1], 6.0);
    assert_eq!(a[2], 6.0);
    assert!(a[3].is_nan());
    assert_eq!(a[4], 0.0);
}

#[test]
fn parser_rejects_guesses() {
    use serde_json::json;
    let bad = [
        json!({"op": "absorbance"}), // clip must be declared
        json!({"op": "absorbance", "clip_min": 0}),
        json!({"op": "savgol", "window": 31, "polyorder": 3, "deriv": 2, "delta": 1.0}), // mode must be declared
        json!({"op": "savgol", "window": 30, "polyorder": 3, "deriv": 2, "delta": 1.0, "mode": "interp"}),
        json!({"op": "savgol", "window": 31, "polyorder": 3, "deriv": 4, "delta": 1.0, "mode": "interp"}),
        json!({"op": "savgol", "window": 31, "polyorder": 3, "deriv": 2, "delta": 1.0, "mode": "bogus"}),
        json!({"op": "savgol", "window": 31, "polyorder": 3, "deriv": 2, "delta": 1.0, "mode": "interp", "edge": 1}),
        json!({"op": "gaussian_blur", "sigma_nm": 3.0}), // radius must be declared
        json!({"op": "crop", "range_nm": [2060, 2030]}),
        json!({"op": "snv", "blocks_nm": [[1600, 1700], [1650, 1800]]}), // overlap
        json!({"op": "snv", "blocks_nm": []}),
        json!({"op": "absorbance_affine", "gain": "x", "clip_min": 1e-6}),
    ];
    for b in bad {
        assert!(
            matches!(parse_op(&b), Err(OpError::InvalidParameters { .. })),
            "{b}"
        );
    }
    let reserved = [
        json!({"op": "snv", "ddof": 0}),
        json!({"op": "gaussian_blur", "fwhm_nm": 8.0, "radius": "ceil"}),
        json!({"op": "gaussian_blur", "sigma_nm": 3.0, "radius": "ceil", "segments": "none"}),
        json!({"op": "msc", "reference": [1, 2, 3]}),
        json!({"op": "detrend"}),
        json!({"op": "resample"}),
        json!({"op": "splice_correct"}),
        json!({"op": "pds_banded"}),
        json!({"op": "affine_reflectance"}),
    ];
    for r in reserved {
        assert!(
            matches!(parse_op(&r), Err(OpError::UnsupportedOperator { .. })),
            "{r}"
        );
    }
}

#[test]
fn savgol_window_longer_than_spectrum_is_an_error() {
    let s = Spectrum::new(vec![1.0, 2.0, 3.0], vec![1.0, 2.0, 3.0]);
    let op = parse_op(&serde_json::json!({"op": "savgol", "window": 5, "polyorder": 2, "deriv": 0, "delta": 1.0, "mode": "mirror"})).unwrap();
    assert!(matches!(
        run_chain(&[op], &s, &[]),
        Err(OpError::Failed { .. })
    ));
}

// ------------------------------------------------------------------ Codex Phase 1 review regressions
#[test]
fn sg_huge_derivative_divisor_is_an_error_not_a_panic() {
    // MEDIUM 1: window 257, polyorder 10, deriv 10 -> 128^10 overflowed u64 (panic in debug)
    let v = serde_json::json!({"op": "savgol", "window": 257, "polyorder": 10, "deriv": 10,
                               "delta": 1.0, "mode": "interp"});
    // the integer power no longer overflows; the divisor is finite, so the op parses
    let op = parse_op(&v).expect("parses");
    let wl: Vec<f64> = (0..600).map(|i| 350.0 + i as f64).collect();
    let x: Vec<f64> = wl.iter().map(|w| 0.3 + 1e-4 * (w * 0.01).sin()).collect();
    // running it either succeeds with finite values or fails cleanly; it never panics
    if let Ok(out) = run_chain(
        &[op],
        &Spectrum::new(wl.clone(), x.clone()),
        &[1000.0, 1800.0],
    ) {
        assert!(out.x.iter().all(|v| v.is_finite()));
    }
    // a delta that makes the divisor overflow to infinity is rejected at parse time
    let v = serde_json::json!({"op": "savgol", "window": 257, "polyorder": 10, "deriv": 10,
                               "delta": 1e40, "mode": "interp"});
    assert!(matches!(
        parse_op(&v),
        Err(OpError::InvalidParameters { .. })
    ));
    assert!(spyder_core::preprocess::savgol::divisor(128, 10, 1.0).is_some());
    assert_eq!(
        spyder_core::preprocess::savgol::divisor(128, 10, 1.0).unwrap(),
        1_180_591_620_717_411_303_424.0
    );
    assert!(spyder_core::preprocess::savgol::divisor(128, 10, 1e40).is_none());
    assert!(spyder_core::preprocess::savgol::try_sg_weights(31, 3, 2, 1.0).is_ok());
}

#[test]
fn blur_radius_wider_than_a_short_segment_is_clipped_not_rejected() {
    // MEDIUM 3: a cropped grid whose SWIR1 segment (1001-1010) is shorter than the kernel radius
    let wl: Vec<f64> = (0..30).map(|i| 990.0 + i as f64).collect(); // 990-1019
    let x: Vec<f64> = wl.iter().map(|w| 0.3 + 0.001 * (w - 990.0)).collect();
    let s = Spectrum::new(wl.clone(), x.clone());
    let joins = [1000.0, 1010.0]; // segments 990-1000, 1001-1010, 1011-1019
    let out = run_chain(
        &[blur(PerSegment::Scalar(25.0), RadiusRule::Ceil)],
        &s,
        &joins,
    )
    .expect("a radius wider than the segment is valid");
    // within each segment the output is a weighted mean of that segment only: bounded by its min/max
    for (a, b) in [(0usize, 11usize), (11, 21), (21, 30)] {
        let (lo, hi) = x[a..b]
            .iter()
            .fold((f64::INFINITY, f64::NEG_INFINITY), |(l, h), &v| {
                (l.min(v), h.max(v))
            });
        for v in &out.x[a..b] {
            assert!(*v >= lo - 1e-15 && *v <= hi + 1e-15, "taps crossed a join");
        }
    }
    // a constant stays constant
    let s = Spectrum::new(wl, vec![0.42; 30]);
    let out = run_chain(
        &[blur(PerSegment::Scalar(1e6), RadiusRule::Round)],
        &s,
        &joins,
    )
    .unwrap();
    assert!(out.x.iter().all(|v| (v - 0.42).abs() <= 1e-15));
}
